RABBIT_PASS: rabbitmqpw
MYSQL_ROOTPASS: mysqlpw
controller_node: 162.13.180.119
compute_node: 162.13.180.119
network_node: 162.13.180.119
MY_PRIVATE_IP: 127.0.0.1
MY_PUBLIC_IP: 162.13.180.119
REGION_NAME: RegionOne
SERVICE_PROJECT: service
NOVA_DBUSER: dbnovau
NOVA_DBPASS: dbnovapw
NOVA_USER: nova
NOVA_PASS: novapw
NEUTRON_DBUSER: dbneutronu
NEUTRON_DBPASS: dbneutronpw
NEUTRON_USER: neutron
NEUTRON_PASS: neutronpw
METADATA_SECRET: mysecret
