# Initial setup

- hosts: openstack-stg

  vars_files:
  - variables.yml

  tasks:
    - name: Updating package list
      apt: update_cache=yes

    - name: Install Ubuntu Cloud Keyring
      action: apt pkg={{item}} state=installed
      with_items:
        - ubuntu-cloud-keyring
        - python-software-properties

    - name: Add Ubuntu Cloud Archive repository for Icehouse
      apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/icehouse main' state=present

    - name: Update all packages to the latest version
      apt: upgrade=dist

    - name: Install Ubuntu backported kernel > 13.10
      action: apt pkg={{item}} state=installed
      with_items:
        - linux-image-generic-lts-saucy 
        - linux-headers-generic-lts-saucy

    - name: Install ntp service
      apt: name=ntp state=present

    - name: Making sure ntp is enabled and running
      service: name=ntp state=started enabled=yes

    - name: Remove old menu.lst
      command: rm -f /boot/grub/menu.lst

    - name: Reboot server to boot new kernel and load openvswitch support
      shell: shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true

    - name: Waiting for server to come back
      local_action: wait_for host={{ inventory_hostname }} port=22 state=started
      sudo: false

