# Installing the Image Service
- hosts: openstack-man

  vars_files:
  - variables.yml

  tasks: 

    - name: Install Glance packages
      apt: name=glance state=latest

    - name: Stop Glance-registry service
      service: name=glance-registry state=stopped enabled=yes

    - name: Stop Glance-api service
      service: name=glance-api state=stopped enabled=yes

    - name: Remove SQLite default db
      shell: rm -f /var/lib/glance/glance.sqlite
    
    - name: Create Glance DB
      mysql_db: name=glance state=present

    - name: Create Glance DB user/pass
      mysql_user: name={{GLANCE_DBUSER}} password={{GLANCE_DBPASS}} priv=glance.*:ALL state=present

    - name: Create Glance Service user
      command: keystone --os-tenant-name {{TENANT_NAME}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} user-create --tenant {{SERVICE_TENANT_NAME}} --name {{GLANCE_USER}} --pass {{GLANCE_PASS}}

    - name: Grant Admin role to Glance user
      command: keystone --os-tenant-name {{TENANT_NAME}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} user-role-add --user {{GLANCE_USER}} --tenant {{SERVICE_TENANT_NAME}} --role-id {{ADMIN_ROLE_NAME}}

    - name: Populate Glance service in service catalog
      command: keystone --os-tenant-name {{TENANT_NAME}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} service-create --name=glance --type=image --description="Glance Image Service"

    - name: Populate Glance endpoint in service catalog
      command: keystone --os-tenant-name {{TENANT_NAME}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} endpoint-create --region RegionOne --service glance --publicurl=http://{{MY_PUBLIC_IP}}:9292/v1 --internalurl=http://{{MY_PRIVATE_IP}}:9292/v1 --adminurl=http://{{MY_PRIVATE_IP}}:9292/v1

    - name: Configure Glance DB access (registry)
      lineinfile: "dest=/etc/glance/glance-registry.conf regexp='^#connection'
                   line='connection = mysql://{{GLANCE_DBUSER}}:{{GLANCE_DBPASS}}@{{MY_PRIVATE_IP}}/glance'"

    - name: Set auth host (registry)
      lineinfile: "dest=/etc/glance/glance-registry.conf regexp='^auth_host'
                   line='auth_host = {{MY_PRIVATE_IP}}'"

    - name: Set admin tenant name (registry)
      lineinfile: "dest=/etc/glance/glance-registry.conf regexp='^admin_tenant_name'
                   line='admin_tenant_name = Services'"

    - name: Set Glance user (registry)
      lineinfile: "dest=/etc/glance/glance-registry.conf regexp='^admin_user' 
                   line='admin_user = {{GLANCE_USER}}'"

    - name: Set Glance password (registry)
      lineinfile: "dest=/etc/glance/glance-registry.conf regexp='^admin_password' 
                   line='admin_password = {{GLANCE_PASS}}'"

    - name: Set flavor (registry)
      lineinfile: "dest=/etc/glance/glance-registry.conf regexp='^#flavor' 
                   line='flavor = keystone'"

    - name: Configure Glance DB access (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^#connection ='
                   line='connection = mysql://{{GLANCE_DBUSER}}:{{GLANCE_DBPASS}}@{{MY_PRIVATE_IP}}/glance'"

    - name: Set Glance auth host (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^auth_host'
                   line='auth_host = {{MY_PRIVATE_IP}}'"

    - name: Set Glance admin tenant name (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^admin_tenant_name'
                   line='admin_tenant_name = Services'"

    - name: Set Glance user (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^admin_user' 
                   line='admin_user = {{GLANCE_USER}}'"

    - name: Set Glance password (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^admin_password' 
                   line='admin_password = {{GLANCE_PASS}}'"

    - name: Set flavor (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^#flavor' 
                   line='flavor = keystone'"

    - name: Set Glance password (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^#show_image_direct_url' 
                   line='show_image_direct_url = True'"

    - name: Set Glance rabbit host (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^rabbit_host'
                   line='rabbit_host = {{MY_PRIVATE_IP}}'"

    - name: Set rabbit password on api config
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^rabbit_password'
                   line='rabbit_password = {{RABBIT_PASS}}'"

    - name: Initialize Glance database
      command: glance-manage db_sync

    - name: Start Glance-registry service
      service: name=glance-registry state=started enabled=yes

    - name: Start Glance-api service
      service: name=glance-api state=started enabled=yes

    - name: Create images directory
      file: path=~/images owner=root state=directory mode=0755

    - name: Download Test Image
      command: wget http://cdn.download.cirros-cloud.net/0.3.2/cirros-0.3.2-x86_64-disk.img -O ~/images/cirros-0.3.2-x86_64-disk.qcow2

    - name: Register a qcow2 image
      command: glance --os-tenant-name {{TENANT_NAME}} --os-username {{MEMBER_USER}} --os-password {{MEMBER_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} image-create --name "cirros-qcow2" --disk-format qcow2 --container-format bare --is-public True --file ~/images/cirros-0.3.2-x86_64-disk.qcow2
