- hosts: openstack-stg
  remote_user: benutzer
  sudo: yes

  vars_files:
  - variables.yml

# Install the Identity Service

  tasks: 

    - name: Install packages
      apt: name=glance state=latest

    - name: Stop Glance-registry service
      service: name=glance-registry state=stopped enabled=yes

    - name: Stop Glance-api service
      service: name=glance-api state=stopped enabled=yes

    - name: Remove SQLite default db
      shell: rm -f /var/lib/glance/glance.sqlite
    
    - name: Create Glance DB
      mysql_db: name=glance state=present

    - name: Create Glance DB user/pass
      mysql_user: name={{ GLANCE_DBUSER }} password={{ GLANCE_DBPASS }} priv=glance.*:ALL state=present

    - name: Create Glance Service user
      command: keystone user-create --tenant {{TENANT_NAME}} --name {{GLANCE_USER}} --pass {{GLANCE_PASS}}
      environment:
        OS_SERVICE_ENDPOINT: http://127.0.0.1:35357/v2.0
        OS_SERVICE_TOKEN: ADMIN

    - name: Grant Admin role to Glance user
      command: keystone user-role-add --user {{GLANCE_USER}} --tenant {{TENANT_NAME}} --role-id {{ADMIN_ROLE_NAME}}
      environment:
        OS_SERVICE_ENDPOINT: http://127.0.0.1:35357/v2.0
        OS_SERVICE_TOKEN: ADMIN

    - name: Populate Glance service in service catalog
      command: keystone service-create --name=glance --type=image --description="Glance Image Service"
      environment:
        OS_SERVICE_ENDPOINT: http://127.0.0.1:35357/v2.0
        OS_SERVICE_TOKEN: ADMIN

    - name: Populate Glance endpoint in service catalog
      command: keystone endpoint-create --region RegionOne --service glance --publicurl=http://{{MY_PUBLIC_IP}}:9292/v1 \
               --internalurl=http://{{MY_PRIVATE_IP}}:9292/v1 --adminurl=http://{{MY_PRIVATE_IP}}:9292/v1
      environment:
        OS_SERVICE_ENDPOINT: http://127.0.0.1:35357/v2.0
        OS_SERVICE_TOKEN: ADMIN

    - name: Configure Glance DB access (registry)
      lineinfile: "dest=/etc/glance/glance-registry.conf regexp='^#connection'
                   line='connection = mysql://{{GLANCE_DBUSER}}:{{GLANCE_DBPASS}}@{{MY_PRIVATE_IP}}/glance'"

    - name: Set auth host (registry)
      lineinfile: "dest=/etc/glance/glance-registry.conf regexp='^auth_host'
                   line='auth_host = {{MY_PRIVATE_IP}}'"

    - name: Set admin tenant name (registry)
      lineinfile: "dest=/etc/glance/glance-registry.conf regexp='^admin_tenant_name'
                   line='admin_tenant_name = Services'"

    - name: Set Glance user (registry)
      lineinfile: "dest=/etc/glance/glance-registry.conf regexp='^admin_user' 
                   line='admin_user = {{GLANCE_USER}}'"

    - name: Set Glance password (registry)
      lineinfile: "dest=/etc/glance/glance-registry.conf regexp='^admin_password' 
                   line='admin_password = {{GLANCE_PASS}}'"

    - name: Set flavor (registry)
      lineinfile: "dest=/etc/glance/glance-registry.conf regexp='^#flavor' 
                   line='flavor = keystone'"

    - name: Configure Glance DB access (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^#connection ='
                   line='connection = mysql://{{GLANCE_DBUSER}}:{{GLANCE_DBPASS}}@{{MY_PRIVATE_IP}}/glance'"

    - name: Set Glance auth host (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^auth_host'
                   line='auth_host = {{MY_PRIVATE_IP}}'"

    - name: Set Glance admin tenant name (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^admin_tenant_name'
                   line='admin_tenant_name = Services'"

    - name: Set Glance user (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^admin_user' 
                   line='admin_user = {{GLANCE_USER}}'"

    - name: Set Glance password (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^admin_password' 
                   line='admin_password = {{GLANCE_PASS}}'"

    - name: Set flavor (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^#flavor' 
                   line='flavor = keystone'"

    - name: Set Glance password (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^#show_image_direct_url' 
                   line='show_image_direct_url = True'"

    - name: Set Glance rabbit host (api)
      lineinfile: "dest=/etc/glance/glance-api.conf regexp='^rabbit_host'
                   line='rabbit_host = {{MY_PRIVATE_IP}}'"

#    - name: Alter table with utf8
#      command: mysql -D glance -e "alter table migrate_version convert to character set utf8 collate utf8_unicode_ci;"

    - name: Initialize Glance database
      command: glance-manage db_sync

    - name: Start Glance-registry service
      service: name=glance-registry state=started enabled=yes

    - name: Start Glance-api service
      service: name=glance-api state=started enabled=yes

    - name: Create Images directory
      file: path=~/Images owner=root state=directory mode=0755

    - name: Download Test Image
      command: wget http://cdn.download.cirros-cloud.net/0.3.2/cirros-0.3.2-x86_64-disk.img -O ~/Images/cirros-0.3.2-x86_64-disk.qcow2


