- hosts: openstack-stg
  remote_user: benutzer
  sudo: yes

  vars_files:
  - variables.yml

# Install the Identity Service

  tasks: 

    - name: Install packages
      apt: name=keystone state=latest

    - name: Stop Keystone service
      service: name=keystone state=stopped enabled=yes

    - name: Remove SQLite default db
      shell: rm -f /var/lib/keystone/keystone.db
    
    - name: Create Keystone DB
      mysql_db: name=keystone state=present

    - name: Create Keystone DB user/pass
      mysql_user: name={{ KEYSTONE_DBUSER }} password={{ KEYSTONE_DBPASS }} priv=keystone.*:ALL state=present

# 
    - name: Configure Keystone DB access
      lineinfile: "dest=/etc/keystone/keystone.conf regexp='^connection'
                   line='connection = mysql://{{KEYSTONE_DBUSER}}:{{KEYSTONE_DBPASS}}@controller/keystone'"

    - name: Set keystone public endpoint URL
      lineinfile: "dest=/etc/keystone/keystone.conf regexp='^public_endpoint' 
                   line='public_endpoint=http://{{MY_PUBLIC_IP}}:%(public_port)'"

    - name: Set keystone admin endpoint URL
      lineinfile: "dest=/etc/keystone/keystone.conf regexp='^admin_endpoint' 
                   line='admin_endpoint=http://{{MY_PRIVATE_IP}}:%(admin_port)'"

    - name: Initialize Keystone database
      shell: keystone-manage db_sync

    - name: Start Keystone service
      service: name=keystone state=started enabled=yes

    - name: Create Main tenant
      command: keystone tenant-create --name {{TENANT_NAME}} 
      environment:
        OS_SERVICE_ENDPOINT: http://127.0.0.1:35357/v2.0
        OS_SERVICE_TOKEN: ADMIN

    - name: Create Service tenant
      command: keystone tenant-create --name {{SERVICE_TENANT_NAME}}
      environment:
        OS_SERVICE_ENDPOINT: http://127.0.0.1:35357/v2.0
        OS_SERVICE_TOKEN: ADMIN

    - name: Create Admin role
      command: keystone role-create --name {{ADMIN_ROLE_NAME}} 
      environment:
        OS_SERVICE_ENDPOINT: http://127.0.0.1:35357/v2.0
        OS_SERVICE_TOKEN: ADMIN

    - name: Create Admin user
      command: keystone user-create --tenant {{TENANT_NAME}} --name {{ADMIN_USER}} --pass {{ADMIN_PASS}}
      environment:
        OS_SERVICE_ENDPOINT: http://127.0.0.1:35357/v2.0
        OS_SERVICE_TOKEN: ADMIN

    - name: Create Non-admin user
      command: keystone user-create --tenant {{TENANT_NAME}} --name {{MEMBER_USER}} --pass {{MEMBER_PASS}}
      environment:
        OS_SERVICE_ENDPOINT: http://127.0.0.1:35357/v2.0
        OS_SERVICE_TOKEN: ADMIN

    - name: Grant Admin role
      command: keystone user-role-add --user {{ADMIN_USER}} --tenant {{TENANT_NAME}} --role-id {{ADMIN_ROLE_NAME}}
      environment:
        OS_SERVICE_ENDPOINT: http://127.0.0.1:35357/v2.0
        OS_SERVICE_TOKEN: ADMIN

    - name: Populate service in service catalog
      command: keystone service-create --name=keystone --type=identity --description="Keystone Identity Service"
      environment:
        OS_SERVICE_ENDPOINT: http://127.0.0.1:35357/v2.0
        OS_SERVICE_TOKEN: ADMIN

    - name: Populate endpoint in service catalog
      command: keystone endpoint-create --region RegionOne --service keystone --publicurl=http://{{MY_PUBLIC_IP}}:5000/v2.0 \
               --internalurl=http://{{MY_PRIVATE_IP}}:5000/v2.0 --adminurl=http://{{MY_PRIVATE_IP}}:35357/v2.0 
      environment:
        OS_SERVICE_ENDPOINT: http://127.0.0.1:35357/v2.0
        OS_SERVICE_TOKEN: ADMIN

    - name: Create credentials directory
      file: path=~/credentials owner=root state=directory mode=0755

    - name: Create user credentials
      copy: src=credentials/user dest=~/credentials/user owner=root group=root mode=0644

    - name: Create admin credentials
      copy: src=credentials/admin dest=~/credentials/admin owner=root group=root mode=0644
