# Configuring bridge and reboot server

- hosts: openstack-stg

  vars_files:
  - variables.yml

  tasks:

    - name: Replacing current interface with a bridge
      replace: dest=/etc/network/interfaces regexp='{{EXT_INTERFACE}}' replace='br-ext'

    - name: Adding auto parameter on current interface
      lineinfile: dest=/etc/network/interfaces insertbefore="^auto br-ext" line='auto {{EXT_INTERFACE}}'
    
    - name: Adding manual flag on current interface
      lineinfile: dest=/etc/network/interfaces insertbefore="^auto br-ext" line='iface {{EXT_INTERFACE}} inet manual'

    - name: Adding ovs type on physical interface
      lineinfile: dest=/etc/network/interfaces insertbefore='^auto br-ext' line='\tovs_type OVSPort'

    - name: Adding ovs bridge on physical interface
      lineinfile: dest=/etc/network/interfaces insertbefore='^auto br-ext' line='\tovs_bridge br-ext'

    - name: Adding link up parameter on current interface
      lineinfile: dest=/etc/network/interfaces insertbefore="^auto br-ext" line='\tup ifconfig $IFACE 0.0.0.0 up'

    - name: Adding promisc mode parameter on current interface
      lineinfile: dest=/etc/network/interfaces insertbefore="^auto br-ext" line='\tup ip link set $IFACE promisc on'

    - name: Adding link down parameter on current interface
      lineinfile: dest=/etc/network/interfaces insertbefore="^auto br-ext" line='\tdown ifconfig $IFACE down\n'

    - name: Adding ovs type on bridge interface
      lineinfile: dest=/etc/network/interfaces insertafter="^auto br-ext" line='\tovs_type OVSBridge'

    - name: Adding ovs bridge on bridge interface
      lineinfile: dest=/etc/network/interfaces insertafter="^auto br-ext" line='\tovs_bridge br-ext'

    - name: Restart server to boot new kernel and restart all services
      shell: shutdown -r now 
      async: 0
      poll: 0
      ignore_errors: true

    - name: Waiting for server to come back
      local_action: wait_for host={{ inventory_hostname }} port=22 state=started
      sudo: false
