# Installing the Image Service

- hosts: openstack-stg

  vars_files:
  - variables.yml

  tasks: 

    - name: Install Heat packages
      action: apt pkg={{item}} state=installed
      with_items:
        - heat-api
        - heat-api-cfn
        - heat-engine

    - name: Remove SQLite default db
      shell: rm -f /var/lib/heat/heat.sqlite
    
    - name: Create Heat DB
      mysql_db: name=heat state=present

    - name: Create Heat DB user/pass
      mysql_user: name={{HEAT_DBUSER}} password={{HEAT_DBPASS}} priv=heat.*:ALL state=present

    - name: Create Heat Service user
      command: keystone --os-tenant-name {{TENANT_NAME}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} user-create --tenant {{SERVICE_TENANT_NAME}} --name {{HEAT_USER}} --pass {{HEAT_PASS}}

    - name: Grant Admin role to Heat user
      command: keystone --os-tenant-name {{TENANT_NAME}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} user-role-add --user {{HEAT_USER}} --tenant {{SERVICE_TENANT_NAME}} --role-id {{ADMIN_ROLE_NAME}}

    - name: Populate Heat service in service catalog
      command: keystone --os-tenant-name {{TENANT_NAME}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} service-create --name=heat --type=orchestration --description="Orchestration"

    - name: Populate heat endpoint in service catalog
      command: keystone --os-tenant-name {{TENANT_NAME}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} endpoint-create --region RegionOne --service heat --publicurl="http://{{MY_PUBLIC_IP}}:8004/v1/%(tenant_id)s" --internalurl="http://{{MY_PRIVATE_IP}}:8004/v1/%(tenant_id)s" --adminurl="http://{{MY_PRIVATE_IP}}:8004/v1/%(tenant_id)s"

    - name: Populate Heat-cfn service in service catalog
      command: keystone --os-tenant-name {{TENANT_NAME}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} service-create --name=heat-cfn --type=cloudformation --description="Orchestration CloudFormation"

    - name: Populate Heat-cfn endpoint in service catalog
      command: keystone --os-tenant-name {{TENANT_NAME}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} endpoint-create --region RegionOne --service heat-cfn --publicurl=http://{{MY_PUBLIC_IP}}:8000/v1 --internalurl=http://{{MY_PRIVATE_IP}}:8000/v1 --adminurl=http://{{MY_PRIVATE_IP}}:8000/v1

    - name: Waiting
      pause: seconds=15

    - name: Create role for heat_stack_user
      command: keystone --os-tenant-name {{TENANT_NAME}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} role-create --name {{HEAT_ROLE}}

    - name: Configure Heat DB access
      lineinfile: dest=/etc/heat/heat.conf regexp='^connection' line='connection = mysql://{{HEAT_DBUSER}}:{{HEAT_DBPASS}}@{{MY_PRIVATE_IP}}/heat'

    - name: Set auth host
      lineinfile: dest=/etc/heat/heat.conf regexp='^#auth_host'
                   line='auth_host = {{MY_PRIVATE_IP}}'

    - name: Set auth port
      lineinfile: dest=/etc/heat/heat.conf regexp='^#auth_port'
                   line='auth_port=35357'

    - name: Set auth port
      lineinfile: dest=/etc/heat/heat.conf regexp='^#auth_protocol'
                   line='auth_protocol=http'

    - name: Set auth URL
      lineinfile: dest=/etc/heat/heat.conf regexp='^#auth_uri' line='auth_uri = http://{{MY_PRIVATE_IP}}:5000/v2.0'

    - name: Set admin tenant name
      lineinfile: dest=/etc/heat/heat.conf regexp='^#admin_tenant_name'
                  line='admin_tenant_name = Services'

    - name: Set Heat user
      lineinfile: dest=/etc/heat/heat.conf regexp='^#admin_user' 
                  line='admin_user = {{HEAT_USER}}'

    - name: Set Heat password
      lineinfile: dest=/etc/heat/heat.conf regexp='^#admin_password'
                  line='admin_password = {{HEAT_PASS}}'

    - name: Set Heat rabbit host
      lineinfile: dest=/etc/heat/heat.conf regexp='^#rabbit_host'
                  line='rabbit_host = {{MY_PRIVATE_IP}}'

    - name: Set rabbit password on config
      lineinfile: dest=/etc/heat/heat.conf regexp='^#rabbit_password'
                  line='rabbit_password = {{RABBIT_PASS}}'

    - name: Set URL of the metadata service
      lineinfile: dest=/etc/heat/heat.conf regexp='^#heat_metadata_server_url' line='heat_metadata_server_url = http://{{MY_PRIVATE_IP}}:8000'

    - name: Set auth URL
      lineinfile: dest=/etc/heat/heat.conf regexp='^#heat_waitcondition_server_url' line='heat_waitcondition_server_url = http://{{MY_PRIVATE_IP}}:8000/v1/waitcondition'

    - name: Set log dir
      lineinfile: dest=/etc/heat/heat.conf regexp='^#logdir' line='log_dir=/var/log/heat'

    - name: Initialize Heat database
      command: heat-manage db_sync

    - name: Start Heat services
      service: name={{item}} state=restarted enabled=yes
      with_items:
        - heat-api
        - heat-api-cfn
        - heat-engine

