# for systems that do not support hardware acceleration
#
- hosts: openstack-stg

  vars_files:
  - variables.yml


  tasks:

    - name: Installing nova qemu support
      apt: name=nova-compute-qemu state=installed

    - name: 
      lineinfile: "dest=/etc/nova/nova-compute.conf regexp='^virt_type' 
                   line='virt_type=qemu'"

    - name: Restart Nova-compute service
      service: name=nova-compute state=restarted enabled=yes

    - name: Download Test Image
      command: wget http://cdn.download.cirros-cloud.net/0.3.2/cirros-0.3.2-x86_64-disk.img -O ~/images/cirros-0.3.2-x86_64-disk.qcow2

    - name: Register a qcow2 image
      command: glance --os-tenant-name {{TENANT_NAME}} --os-username {{MEMBER_USER}} --os-password {{MEMBER_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} image-create --name "cirros-qcow2" --disk-format qcow2 --container-format bare --is-public True --file ~/images/cirros-0.3.2-x86_64-disk.qcow2

