# Creating and instance and applying sec rules

- hosts: openstack-stg

  vars_files:
  - variables.yml

  tasks:

    - name: Boot an instance using flavor and image names
      command: nova --os-tenant-name {{TENANT_NAME}} --os-username {{MEMBER_USER}} --os-password {{MEMBER_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} boot --image centos-6.6-qcow2 --flavor m1.small --key-name MyKey MyFirstInstance 

    - name: Update default security group to allow host access to guest subnet
      command: neutron --os-tenant-name {{TENANT_NAME}} --os-username {{MEMBER_USER}} --os-password {{MEMBER_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} security-group-rule-create --direction ingress --ethertype IPv4 --protocol tcp --port-range-min 22 --port-range-max 22 --remote-ip-prefix {{INS_PRIV_SUBNET}} default

    - name: Update default security group to allow host access to guest subnet
      command: neutron --os-tenant-name {{TENANT_NAME}} --os-username {{MEMBER_USER}} --os-password {{MEMBER_PASS}} --os-auth-url {{AUTH_URL}} --os-region-name {{REGION_NAME}} security-group-rule-create --direction ingress --ethertype IPv4 --protocol icmp --remote-ip-prefix {{INS_PRIV_SUBNET}} default



